version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: widen
    groups:
      development-dependencies:
        dependency-type: "development"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase-if-necessary
    ignore:
      - update-types:
          - "version-update:semver-major"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
