version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: widen
    groups:
      development-dependencies:
        dependency-type: "development"
        versioning-strategy: widen
      production-dependencies:
        dependency-type: "production"
        versioning-strategy: increase-if-necessary
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
