name: Release Package
on:
  push:
    tags:
      - v*

  workflow_dispatch:
    inputs:
      isDryRun:
        description: "Is this a dry run?"
        type: boolean
        required: true
        default: true

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get package version
        id: get-package-version
        shell: bash
        run: |
          echo "version=$(cat package.json  | jq -r .version)" >> $GITHUB_OUTPUT

      - name: Ensure tag matches package versions
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          test "${{ github.ref_name }}" == "v${{ steps.get-package-version.outputs.version }}"

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          tag: "${{ github.ref_name }}"
          generateReleaseNotes: true
          makeLatest: true

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: read
      id-token: write

    # only allow running this workflow from main
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package (dry-run)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.isDryRun }}
        run: npm publish --provenance --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        if: ${{ github.event_name == 'push' || github.event.inputs.isDryRun == 'false' }}
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
