name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      additionalArgs:
        description: 'Additional arguments to pass into npm publish command'
        required: false
        default: ''

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get package version
        id: get-package-version
        shell: bash
        run: |
          run: echo "version=$(cat package.json  | jq -r .version)" >> $GITHUB_OUTPUT

      - name: Generate release tag
        id: tag
        uses: amitsingh-007/next-release-tag@c66ea2293d1764a8aa12f878166f7a8d124a3992
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          tag_template: ${{ steps.get-package-version.outputs.version }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.next_release_tag }}
          generateReleaseNotes: true
          makeLatest: true

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package
        run: npm publish --provenance --access public ${{ github.event.inputs.additionalArgs }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
